### ISSUE TITLE
Looks like this isn't compatible with es6 modules?

### ISSUE THREAD

**Issue by spalger** [MrHen/typings-del#3] opened 2016-06-07 15:09 UTC
![image](https://cloud.githubusercontent.com/assets/1329312/15863276/30ccd24e-2c87-11e6-9539-078608843240.png)

**Comment by MrHen** [comment] 2016-06-07 15:27
You should be able to do `import * as del from 'del'`.

**Comment by spalger** [comment] 2016-06-07 15:28
I can, but then I get a different error: 
![image](https://cloud.githubusercontent.com/assets/1329312/15863947/dbcace24-2c89-11e6-903f-82dd81cf50bc.png)

**Comment by spalger** [comment] 2016-06-07 15:29
Also, doesn't it seem wrong to import a function as a namespace?

**Comment by MrHen** [comment] 2016-06-07 15:36
Well, yeah, it does seem odd. I was only ever using `import del = require('del')`. I'll try to take a look at it tonight.

**Comment by MrHen** [comment] 2016-06-07 23:27
@spalger I was able to use `import * as del from 'del'` without any issues:

```
import * as del from 'del';

test('del (string parameter)', (t) => {
  t.plan(1);
  del(['tmp/*.js', '!tmp/unicorn.js']);
  t.assert(1 === 1);
});
```

Of note, [del itself](https://github.com/sindresorhus/del/blob/master/index.js) does not have a default export which is why I did not add one to the typings.

It is possible that you are seeing an IDE specific issue. Are you able to run the TypeScript compile?

**Comment by spalger** [comment] 2016-06-07 23:28
Possibly, I'm too noob to know really

**Comment by MrHen** [comment] 2016-06-09 20:44
The typings appears correct based on my local testing; I'm closing this issue. The problem is probably in your IDE configuration somewhere.

**Closed as completed by MrHen** 2016-06-09 20:44 UTC
